name: 💡 Feature Request
description: Suggest an idea for this project
title: '[FEATURE] '
labels: ['enhancement']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: feature_request
    attributes:
      label: Feature Request
      description: A clear and concise description of the feature you want to see, what it would allow you to do, and why it would be useful.
      placeholder: I would like to see a feature that allows me to...
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
